// 此文件由脚本自动生成，请勿手动修改
// 来源: @zstack/icon

import {
  AppIconAccessControl,
  AppIconAftersale,
  AppIconAiStore,
  AppIconAliyun,
  AppIconApplicationCenter,
  AppIconArm64,
  AppIconAutomatedOm,
  AppIconBackup,
  AppIconBackupManagement,
  AppIconBaremetal,
  AppIconBillingManagement,
  AppIconCloudFormation,
  AppIconCloudMonitoring,
  AppIconCryptoCompliance,
  AppIconDefaultApp,
  AppIconDistributedStorage,
  AppIconElasticBaremetal,
  AppIconEnterpriseManagement,
  AppIconHardware,
  AppIconInspection,
  AppIconMarketplace,
  AppIconMessageLog,
  AppIconMigrationService,
  AppIconNetworkResource,
  AppIconNetworkService,
  AppIconNetworkTopology,
  AppIconPlatformCryptoCmpl,
  AppIconResourcePool,
  AppIconSettings,
  AppIconTagManagement,
  AppIconWizard,
} from "./app-icons";
import type { IconComponent } from "./icon-component";

export const AppIcons = {
  "access-control": AppIconAccessControl,
  aftersale: AppIconAftersale,
  "ai-store": AppIconAiStore,
  aliyun: AppIconAliyun,
  "application-center": AppIconApplicationCenter,
  "arm-64": AppIconArm64,
  "automated-om": AppIconAutomatedOm,
  backup: AppIconBackup,
  "backup-management": AppIconBackupManagement,
  baremetal: AppIconBaremetal,
  "billing-management": AppIconBillingManagement,
  "cloud-formation": AppIconCloudFormation,
  "cloud-monitoring": AppIconCloudMonitoring,
  "crypto-compliance": AppIconCryptoCompliance,
  "default-app": AppIconDefaultApp,
  hardware: AppIconHardware,
  inspection: AppIconInspection,
  marketplace: AppIconMarketplace,
  "message-log": AppIconMessageLog,
  "migration-service": AppIconMigrationService,
  "network-resource": AppIconNetworkResource,
  "network-service": AppIconNetworkService,
  "network-topology": AppIconNetworkTopology,
  "platform-crypto-cmpl": AppIconPlatformCryptoCmpl,
  "resource-pool": AppIconResourcePool,
  settings: AppIconSettings,
  "tag-management": AppIconTagManagement,
  wizard: AppIconWizard,
} satisfies Record<string, IconComponent>;
