// 此文件由脚本自动生成，请勿手动修改
// 来源: @zstack/icon

import type { IconComponent } from "./icon-component";
import {
  IconActivity,
  IconAiServer,
  IconAlarm,
  IconAlarmButton,
  IconAlarmButtonFill,
  IconAlarmFill,
  IconAlertTriangle,
  IconAlertTriangleFill,
  IconAliyun,
  IconAll,
  IconAllDone,
  IconAlmalinux,
  IconAnalysis,
  IconAnalysisFill,
  IconAnolisos,
  IconApplication,
  IconArchive,
  IconArchiveFill,
  IconArrowCircleDown,
  IconArrowCircleDownFill,
  IconArrowCircleLeft,
  IconArrowCircleLeftFill,
  IconArrowCircleRight,
  IconArrowCircleRightFill,
  IconArrowCircleUp,
  IconArrowCircleUpFill,
  IconArrowDown,
  IconArrowDownFill,
  IconArrowDownOutline,
  IconArrowhead,
  IconArrowheadDown,
  IconArrowheadLeft,
  IconArrowheadRight,
  IconArrowheadUp,
  IconArrowIosDown,
  IconArrowIosLeft,
  IconArrowIosRight,
  IconArrowIosUp,
  IconArrowLeft,
  IconArrowRight,
  IconArrowRightFill,
  IconArrowRightOutline,
  IconArrowUp,
  IconArrowUpFill,
  IconArrowUpOutline,
  IconArrrowLeftFill,
  IconArrrowLeftOutline,
  IconAt,
  IconAttach,
  IconAttach2,
  IconAudit,
  IconAuthority,
  IconAuthorityFill,
  IconAward,
  IconAwardFill,
  IconBackspace,
  IconBackspaceFill,
  IconBackup,
  IconBackupFill,
  IconBarChart,
  IconBarChart2,
  IconBarChart2Invert,
  IconBarChart3,
  IconBattery,
  IconBatteryFill,
  IconBattteryCharging,
  IconBattteryChargingFill,
  IconBell,
  IconBellFill,
  IconBellOff,
  IconBellOffFill,
  IconBeta,
  IconBill,
  IconBillFill,
  IconBluetooth,
  IconBold,
  IconBook,
  IconBookFill,
  IconBookmark,
  IconBookmarkFill,
  IconBookOpen,
  IconBookOpenFill,
  IconBriefcase,
  IconBriefcaseFill,
  IconBrowser,
  IconBrowser2,
  IconBrowser2Fill,
  IconBrowserFill,
  IconBrush,
  IconBrushFill,
  IconBuilding,
  IconBulb,
  IconBulbFill,
  IconByGroup,
  IconCalendar,
  IconCalendarFill,
  IconCamera,
  IconCameraFill,
  IconCameras,
  IconCamerasFill,
  IconCar,
  IconCaretDown,
  IconCaretUp,
  IconCarFill,
  IconCast,
  IconCd,
  IconCdFill,
  IconCentos,
  IconCentosstream,
  IconCertificate,
  IconCertificateFill,
  IconChain,
  IconChain2,
  IconChain2Fill,
  IconChain3,
  IconChain3Fill,
  IconChain4,
  IconChain4Fill,
  IconChain5,
  IconChainFill,
  IconCheckmark,
  IconCheckmark2,
  IconCheckmarkCircle,
  IconCheckmarkCircle2,
  IconCheckmarkCircleFill,
  IconCheckmarkSquare,
  IconCheckmarkSquare2,
  IconCheckmarkSquareFill,
  IconCircleUndo,
  IconCircleUndoFill,
  IconClean,
  IconClipboard,
  IconClipboardFill,
  IconClock,
  IconClockFill,
  IconClose,
  IconCloseCircle,
  IconCloseCircleFill,
  IconCloseSquare,
  IconCloseSquareFill,
  IconCloud,
  IconCloudDownload,
  IconCloudDownloadFill,
  IconCloudFill,
  IconCloudUpload,
  IconCloudUploadFill,
  IconCode,
  IconCodeDownload,
  IconCollapse,
  IconColorPalette,
  IconColorPaletteFill,
  IconColorPicker,
  IconColorPickerFill,
  IconCompass,
  IconCompassFill,
  IconConsole,
  IconConsole2,
  IconConsole2Fill,
  IconContainer,
  IconContainerGroup,
  IconConvergence,
  IconCopy,
  IconCopyFill,
  IconCoreos,
  IconCornerDownLeft,
  IconCornerDownRight,
  IconCornerLeftDown,
  IconCornerLeftUp,
  IconCornerRightDown,
  IconCornerRightUp,
  IconCornerUpLeft,
  IconCornerUpRight,
  IconCpu,
  IconCreditCard,
  IconCreditCardFill,
  IconCrop,
  IconCube,
  IconCubeFill,
  IconDashboard,
  IconData,
  IconDataset,
  IconDebian,
  IconDeploy,
  IconDeploymentList,
  IconDiagonalArrowLeftDown,
  IconDiagonalArrowLeftUp,
  IconDiagonalArrowRightDown,
  IconDiagonalArrowRightUp,
  IconDisk,
  IconDisk2,
  IconDisk2Fill,
  IconDiskFill,
  IconDiskOffering,
  IconDiskOfferingFill,
  IconDispatch,
  IconDistributedstorage,
  IconDownload,
  IconDportgroup,
  IconDPortgroup,
  IconDrag,
  IconDroplet,
  IconDropletFill,
  IconDropletOff,
  IconDropletOffFill,
  IconDswitch,
  IconEdit,
  IconEdit2,
  IconEdit2Fill,
  IconEditFill,
  IconEditor,
  IconEditorFill,
  IconElasticity,
  IconEmail,
  IconEmailFill,
  IconEncircle,
  IconEncircleFill,
  IconError,
  IconExecuting,
  IconExpand,
  IconExpand3,
  IconExpend,
  IconExternalLink,
  IconEye,
  IconEyeFill,
  IconEyeOff,
  IconEyeOffFill,
  IconFedora,
  IconFile,
  IconFileAdd,
  IconFileAddFill,
  IconFileBan,
  IconFileEdit,
  IconFileFill,
  IconFileLogin,
  IconFilePaste,
  IconFileRemove,
  IconFileRemoveFill,
  IconFileText,
  IconFileTextFill,
  IconFilm,
  IconFilmFill,
  IconFineTuning,
  IconFire,
  IconFireFill,
  IconFlag,
  IconFlagFill,
  IconFlash,
  IconFlashFill,
  IconFlashOff,
  IconFlashOffFill,
  IconFlip,
  IconFold,
  IconFold1,
  IconFolder,
  IconFolderAdd,
  IconFolderAddFill,
  IconFolderFill,
  IconFolderRemove,
  IconFolderRemoveFill,
  IconFreebsd,
  IconFullscreen,
  IconFunnel,
  IconFunnelFill,
  IconGift,
  IconGiftFill,
  IconGlobe,
  IconGlobe2,
  IconGlobe2Fill,
  IconGpu,
  IconGpuFill,
  IconGpuOffering,
  IconGpuOfferingFill,
  IconGrid,
  IconGrid2,
  IconGridFill,
  IconGroup,
  IconGroupFill,
  IconHardDiskImage,
  IconHardDrive,
  IconHardDriveFill,
  IconHardDriveOffering,
  IconHardDrives,
  IconHash,
  IconHastrategic,
  IconHastrategicZsv,
  IconHeadphones,
  IconHeadphonesFill,
  IconHeart,
  IconHeartFill,
  IconHeight,
  IconHistory,
  IconHistoryFill,
  IconHome,
  IconHomeFill,
  IconHourglass,
  IconImage,
  IconImageFill,
  IconInbox,
  IconInboxFill,
  IconInferenceTemplate,
  IconInfo,
  IconInfoFill,
  IconInterface,
  IconInterfaceFill,
  IconIp,
  IconIp2,
  IconIpFill,
  IconItalic,
  IconKernelPortgroup,
  IconKey,
  IconKeyFill,
  IconKeypad,
  IconKeypadFill,
  IconKnife,
  IconKylin,
  IconLayers,
  IconLayersFill,
  IconLayout,
  IconLayoutFill,
  IconLayoutLeft,
  IconLink,
  IconLinked,
  IconLinux,
  IconList,
  IconListNumeral,
  IconLlmops,
  IconLoader,
  IconLocate,
  IconLock,
  IconLockFill,
  IconLogCollect,
  IconLogIn,
  IconLogOut,
  IconMailReceive,
  IconMailReceiveFill,
  IconMap,
  IconMapFill,
  IconMaximize,
  IconMaximizeFill,
  IconMemory,
  IconMenu,
  IconMenu2,
  IconMenuArrowLeft,
  IconMenuArrowRight,
  IconMessageCircle,
  IconMessageCircleFill,
  IconMessageSquare,
  IconMessageSquareFill,
  IconMic,
  IconMicFill,
  IconMicOff,
  IconMicOffFill,
  IconMigrate,
  IconMigrateFill,
  IconMigrationResource,
  IconMigrationService,
  IconMigrationServiceFill,
  IconMinimize,
  IconMinimizeFill,
  IconMinus,
  IconMinusCircle,
  IconMinusCircleFill,
  IconMinusSquare,
  IconMinusSquareFill,
  IconModelSquare,
  IconModelTest,
  IconMonitor,
  IconMonitorFill,
  IconMonitorOffering,
  IconMonitorOfferingFill,
  IconMonitors,
  IconMoon,
  IconMoonFill,
  IconMoreHorizontal,
  IconMoreVertical,
  IconMove,
  IconMusic,
  IconMusicFill,
  IconMyApprovals,
  IconNavigation,
  IconNavigation2,
  IconNavigation2Fill,
  IconNavigationFill,
  IconNetworkCard,
  IconNetworkPort,
  IconNetworkPortUnfill,
  IconNode,
  IconNode2,
  IconNode2Fill,
  IconNode3,
  IconNodeFill,
  IconNpm,
  IconNpmFill,
  IconNut,
  IconNutFill,
  IconOpeneuler,
  IconOpensuse,
  IconOptions,
  IconOptions2,
  IconOptions2Fill,
  IconOptionsFill,
  IconOracle,
  IconOutlet,
  IconOutletFill,
  IconPantone,
  IconPantoneFill,
  IconPaperPlane,
  IconParameter,
  IconParameterOff,
  IconParavirtualization,
  IconParavirtualizationFill,
  IconPauseCircle,
  IconPauseCircleFill,
  IconPeople,
  IconPeopleFill,
  IconPercent,
  IconPerson,
  IconPersonAdd,
  IconPersonAddFill,
  IconPersonAdmin,
  IconPersonAdminFill,
  IconPersonCircle,
  IconPersonCircleFill,
  IconPersonDelete,
  IconPersonDeleteFill,
  IconPersonDone,
  IconPersonDoneFill,
  IconPersonFill,
  IconPersonRemove,
  IconPersonRemoveFill,
  IconPhone,
  IconPhoneCall,
  IconPhoneCallFill,
  IconPhoneFill,
  IconPhoneMissed,
  IconPhoneMissedFill,
  IconPhoneOff,
  IconPhoneOffFill,
  IconPieChart,
  IconPieChartFill,
  IconPin,
  IconPin2,
  IconPinFill,
  IconPlayCircle,
  IconPlayCircleFill,
  IconPlugin,
  IconPlus,
  IconPlusCircle,
  IconPlusCircleFill,
  IconPlusSquare,
  IconPlusSquareFill,
  IconPower,
  IconPricetag,
  IconPricetagFill,
  IconPricetags,
  IconPrinter,
  IconPrinterFill,
  IconProgress,
  IconProgressFill,
  IconQcode,
  IconQuestionMark,
  IconQuestionMarkCircle,
  IconQuestionMarkCircleFill,
  IconQuestionnaire,
  IconRadio,
  IconRadioButtonOff,
  IconRadioButtonOffDisabled,
  IconRadioButtonOn,
  IconRadioButtonOnFill,
  IconRadioFill,
  IconRecovery,
  IconRedhat,
  IconRedo,
  IconRedoFill,
  IconRefresh,
  IconRepeat,
  IconRestore,
  IconRewindLeft,
  IconRewindLeftFill,
  IconRewindRight,
  IconRewindRightFill,
  IconRockylinux,
  IconRouter,
  IconRouterFill,
  IconRouterLaunch,
  IconRouterLaunchFill,
  IconRouterOffering,
  IconRouterOfferingFill,
  IconRouters,
  IconRoutersFill,
  IconScan,
  IconScissors,
  IconScriptLibrary,
  IconSearch,
  IconSelect,
  IconServer,
  IconServer1,
  IconServer1Fill,
  IconServer2,
  IconServer2Fill,
  IconServer3,
  IconServer3Fill,
  IconServer4,
  IconServerFill,
  IconServers3,
  IconSettings,
  IconSettings2,
  IconSettings2Fill,
  IconSettingsFill,
  IconShake,
  IconShare,
  IconShareFill,
  IconShield,
  IconShield1,
  IconShield2Fill,
  IconShieldFill,
  IconShieldOff,
  IconShieldOffFill,
  IconShoppingBag,
  IconShoppingBagFill,
  IconShoppingCart,
  IconShoppingCartFill,
  IconShuffle,
  IconShuffle2,
  IconShutterFill,
  IconSkipBack,
  IconSkipBackFill,
  IconSkipForward,
  IconSkipForwardFill,
  IconSlash,
  IconSlot,
  IconSlotFill,
  IconSmartphone,
  IconSmartphoneFill,
  IconSnmp,
  IconSocket,
  IconSocketFill,
  IconSolaris,
  IconSort,
  IconSource,
  IconSourceFill,
  IconSourceGroup,
  IconSourceGroupFill,
  IconSpeaker,
  IconSpeakerFill,
  IconSquare,
  IconStablity,
  IconStablityFill,
  IconStar,
  IconStarFill,
  IconStopCircle,
  IconStopCircleFill,
  IconStorage,
  IconStorage2,
  IconStorage2Fill,
  IconStorage3,
  IconStorage3Fill,
  IconStorage4,
  IconStorageFill,
  IconSubset,
  IconSubsetFill,
  IconSuccess,
  IconSun,
  IconSunFill,
  IconSuse,
  IconSustain,
  IconSwap,
  IconSwap2,
  IconSync,
  IconSystemTranslation,
  IconSystemTranslationFill,
  IconTags,
  IconTagsFill,
  IconTask,
  IconText,
  IconThermometer,
  IconThermometerFill,
  IconThermometerMinus,
  IconThermometerMinusFill,
  IconThermometerPlus,
  IconThermometerPlusFill,
  IconTimedTask,
  IconTimedTaskFill,
  IconTimer,
  IconTimerFill,
  IconToBottom,
  IconToggleLeft,
  IconToggleLeftFill,
  IconToggleRight,
  IconToggleRightFill,
  IconTopology,
  IconTopology2,
  IconTopology2Fill,
  IconTopologyFill,
  IconToTop,
  IconTrash,
  IconTrashFill,
  IconTree,
  IconTrendingDown,
  IconTrendingUp,
  IconTunnel,
  IconTunnelFill,
  IconTv,
  IconTvFill,
  IconUbuntu,
  IconUmbrella,
  IconUmbrellaFill,
  IconUnderline,
  IconUndo,
  IconUndoFill,
  IconUngroup,
  IconUngroupFill,
  IconUnlock,
  IconUnlockFill,
  IconUos,
  IconUpload,
  IconUsb,
  IconUserRegistrationTermBg,
  IconVcenter,
  IconVersion,
  IconVersionCheckbg,
  IconVessel,
  IconVesselFill,
  IconVgpuOffering,
  IconVgpuOfferingFill,
  IconVideo,
  IconVideoFill,
  IconVideoOff,
  IconVideoOffFill,
  IconVolume,
  IconVolumeDown,
  IconVolumeDownFill,
  IconVolumeFill,
  IconVolumeOff,
  IconVolumeOffFill,
  IconVolumeUp,
  IconVolumeUpFill,
  IconVyos,
  IconWall,
  IconWallFill,
  IconWebShell,
  IconWeight,
  IconWeightFill,
  IconWifi,
  IconWifiOff,
  IconWindows,
  IconWizard,
  IconWrench,
  IconWrenchCircleFill,
  IconWrenchFill,
  IconXmlHook,
} from "./icons";

export const Icons = {
  activity: IconActivity,
  "ai-server": IconAiServer,
  alarm: IconAlarm,
  "alarm-button": IconAlarmButton,
  "alarm-button-fill": IconAlarmButtonFill,
  "alarm-fill": IconAlarmFill,
  "alert-triangle": IconAlertTriangle,
  "alert-triangle-fill": IconAlertTriangleFill,
  aliyun: IconAliyun,
  all: IconAll,
  "all-done": IconAllDone,
  almalinux: IconAlmalinux,
  analysis: IconAnalysis,
  "analysis-fill": IconAnalysisFill,
  anolisos: IconAnolisos,
  application: IconApplication,
  archive: IconArchive,
  "archive-fill": IconArchiveFill,
  "arrow-circle-down": IconArrowCircleDown,
  "arrow-circle-down-fill": IconArrowCircleDownFill,
  "arrow-circle-left": IconArrowCircleLeft,
  "arrow-circle-left-fill": IconArrowCircleLeftFill,
  "arrow-circle-right": IconArrowCircleRight,
  "arrow-circle-right-fill": IconArrowCircleRightFill,
  "arrow-circle-up": IconArrowCircleUp,
  "arrow-circle-up-fill": IconArrowCircleUpFill,
  "arrow-down": IconArrowDown,
  "arrow-down-fill": IconArrowDownFill,
  "arrow-down-outline": IconArrowDownOutline,
  arrowhead: IconArrowhead,
  "arrowhead-down": IconArrowheadDown,
  "arrowhead-left": IconArrowheadLeft,
  "arrowhead-right": IconArrowheadRight,
  "arrowhead-up": IconArrowheadUp,
  "arrow-ios-down": IconArrowIosDown,
  "arrow-ios-left": IconArrowIosLeft,
  "arrow-ios-right": IconArrowIosRight,
  "arrow-ios-up": IconArrowIosUp,
  "arrow-left": IconArrowLeft,
  "arrow-right": IconArrowRight,
  "arrow-right-fill": IconArrowRightFill,
  "arrow-right-outline": IconArrowRightOutline,
  "arrow-up": IconArrowUp,
  "arrow-up-fill": IconArrowUpFill,
  "arrow-up-outline": IconArrowUpOutline,
  "arrrow-left-fill": IconArrrowLeftFill,
  "arrrow-left-outline": IconArrrowLeftOutline,
  at: IconAt,
  attach: IconAttach,
  "attach-2": IconAttach2,
  audit: IconAudit,
  authority: IconAuthority,
  "authority-fill": IconAuthorityFill,
  award: IconAward,
  "award-fill": IconAwardFill,
  backspace: IconBackspace,
  "backspace-fill": IconBackspaceFill,
  backup: IconBackup,
  "backup-fill": IconBackupFill,
  "bar-chart": IconBarChart,
  "bar-chart-2": IconBarChart2,
  "bar-chart-2-invert": IconBarChart2Invert,
  "bar-chart-3": IconBarChart3,
  battery: IconBattery,
  "battery-fill": IconBatteryFill,
  "batttery-charging": IconBattteryCharging,
  "batttery-charging-fill": IconBattteryChargingFill,
  bell: IconBell,
  "bell-fill": IconBellFill,
  "bell-off": IconBellOff,
  "bell-off-fill": IconBellOffFill,
  beta: IconBeta,
  bill: IconBill,
  "bill-fill": IconBillFill,
  bluetooth: IconBluetooth,
  bold: IconBold,
  book: IconBook,
  "book-fill": IconBookFill,
  bookmark: IconBookmark,
  "bookmark-fill": IconBookmarkFill,
  "book-open": IconBookOpen,
  "book-open-fill": IconBookOpenFill,
  briefcase: IconBriefcase,
  "briefcase-fill": IconBriefcaseFill,
  browser: IconBrowser,
  "browser-2": IconBrowser2,
  "browser-2-fill": IconBrowser2Fill,
  "browser-fill": IconBrowserFill,
  brush: IconBrush,
  "brush-fill": IconBrushFill,
  building: IconBuilding,
  bulb: IconBulb,
  "bulb-fill": IconBulbFill,
  "by-group": IconByGroup,
  calendar: IconCalendar,
  "calendar-fill": IconCalendarFill,
  camera: IconCamera,
  "camera-fill": IconCameraFill,
  cameras: IconCameras,
  "cameras-fill": IconCamerasFill,
  car: IconCar,
  "caret-down": IconCaretDown,
  "caret-up": IconCaretUp,
  "car-fill": IconCarFill,
  cast: IconCast,
  cd: IconCd,
  "cd-fill": IconCdFill,
  centos: IconCentos,
  centosstream: IconCentosstream,
  certificate: IconCertificate,
  "certificate-fill": IconCertificateFill,
  chain: IconChain,
  "chain-2": IconChain2,
  "chain-2-fill": IconChain2Fill,
  "chain-3": IconChain3,
  "chain-3-fill": IconChain3Fill,
  "chain-4": IconChain4,
  "chain-4-fill": IconChain4Fill,
  "chain-5": IconChain5,
  "chain-fill": IconChainFill,
  checkmark: IconCheckmark,
  "checkmark-2": IconCheckmark2,
  "checkmark-circle": IconCheckmarkCircle,
  "checkmark-circle-2": IconCheckmarkCircle2,
  "checkmark-circle-fill": IconCheckmarkCircleFill,
  "checkmark-square": IconCheckmarkSquare,
  "checkmark-square-2": IconCheckmarkSquare2,
  "checkmark-square-fill": IconCheckmarkSquareFill,
  "circle-undo": IconCircleUndo,
  "circle-undo-fill": IconCircleUndoFill,
  clean: IconClean,
  clipboard: IconClipboard,
  "clipboard-fill": IconClipboardFill,
  clock: IconClock,
  "clock-fill": IconClockFill,
  close: IconClose,
  "close-circle": IconCloseCircle,
  "close-circle-fill": IconCloseCircleFill,
  "close-square": IconCloseSquare,
  "close-square-fill": IconCloseSquareFill,
  cloud: IconCloud,
  "cloud-download": IconCloudDownload,
  "cloud-download-fill": IconCloudDownloadFill,
  "cloud-fill": IconCloudFill,
  "cloud-upload": IconCloudUpload,
  "cloud-upload-fill": IconCloudUploadFill,
  code: IconCode,
  "code-download": IconCodeDownload,
  collapse: IconCollapse,
  "color-palette": IconColorPalette,
  "color-palette-fill": IconColorPaletteFill,
  "color-picker": IconColorPicker,
  "color-picker-fill": IconColorPickerFill,
  compass: IconCompass,
  "compass-fill": IconCompassFill,
  console: IconConsole,
  "console-2": IconConsole2,
  "console-2-fill": IconConsole2Fill,
  container: IconContainer,
  "container-group": IconContainerGroup,
  convergence: IconConvergence,
  copy: IconCopy,
  "copy-fill": IconCopyFill,
  coreos: IconCoreos,
  "corner-down-left": IconCornerDownLeft,
  "corner-down-right": IconCornerDownRight,
  "corner-left-down": IconCornerLeftDown,
  "corner-left-up": IconCornerLeftUp,
  "corner-right-down": IconCornerRightDown,
  "corner-right-up": IconCornerRightUp,
  "corner-up-left": IconCornerUpLeft,
  "corner-up-right": IconCornerUpRight,
  cpu: IconCpu,
  "credit-card": IconCreditCard,
  "credit-card-fill": IconCreditCardFill,
  crop: IconCrop,
  cube: IconCube,
  "cube-fill": IconCubeFill,
  dashboard: IconDashboard,
  data: IconData,
  dataset: IconDataset,
  debian: IconDebian,
  deploy: IconDeploy,
  "deployment-list": IconDeploymentList,
  "diagonal-arrow-left-down": IconDiagonalArrowLeftDown,
  "diagonal-arrow-left-up": IconDiagonalArrowLeftUp,
  "diagonal-arrow-right-down": IconDiagonalArrowRightDown,
  "diagonal-arrow-right-up": IconDiagonalArrowRightUp,
  disk: IconDisk,
  "disk-2": IconDisk2,
  "disk-2-fill": IconDisk2Fill,
  "disk-fill": IconDiskFill,
  "disk-offering": IconDiskOffering,
  "disk-offering-fill": IconDiskOfferingFill,
  dispatch: IconDispatch,
  distributedstorage: IconDistributedstorage,
  download: IconDownload,
  dportgroup: IconDportgroup,
  "d-portgroup": IconDPortgroup,
  drag: IconDrag,
  droplet: IconDroplet,
  "droplet-fill": IconDropletFill,
  "droplet-off": IconDropletOff,
  "droplet-off-fill": IconDropletOffFill,
  dswitch: IconDswitch,
  edit: IconEdit,
  "edit-2": IconEdit2,
  "edit-2-fill": IconEdit2Fill,
  "edit-fill": IconEditFill,
  editor: IconEditor,
  "editor-fill": IconEditorFill,
  elasticity: IconElasticity,
  email: IconEmail,
  "email-fill": IconEmailFill,
  encircle: IconEncircle,
  "encircle-fill": IconEncircleFill,
  error: IconError,
  executing: IconExecuting,
  expand: IconExpand,
  "expand-3": IconExpand3,
  expend: IconExpend,
  "external-link": IconExternalLink,
  eye: IconEye,
  "eye-fill": IconEyeFill,
  "eye-off": IconEyeOff,
  "eye-off-fill": IconEyeOffFill,
  fedora: IconFedora,
  file: IconFile,
  "file-add": IconFileAdd,
  "file-add-fill": IconFileAddFill,
  "file-ban": IconFileBan,
  "file-edit": IconFileEdit,
  "file-fill": IconFileFill,
  "file-login": IconFileLogin,
  "file-paste": IconFilePaste,
  "file-remove": IconFileRemove,
  "file-remove-fill": IconFileRemoveFill,
  "file-text": IconFileText,
  "file-text-fill": IconFileTextFill,
  film: IconFilm,
  "film-fill": IconFilmFill,
  "fine-tuning": IconFineTuning,
  fire: IconFire,
  "fire-fill": IconFireFill,
  flag: IconFlag,
  "flag-fill": IconFlagFill,
  flash: IconFlash,
  "flash-fill": IconFlashFill,
  "flash-off": IconFlashOff,
  "flash-off-fill": IconFlashOffFill,
  flip: IconFlip,
  fold: IconFold,
  "fold-1": IconFold1,
  folder: IconFolder,
  "folder-add": IconFolderAdd,
  "folder-add-fill": IconFolderAddFill,
  "folder-fill": IconFolderFill,
  "folder-remove": IconFolderRemove,
  "folder-remove-fill": IconFolderRemoveFill,
  freebsd: IconFreebsd,
  fullscreen: IconFullscreen,
  funnel: IconFunnel,
  "funnel-fill": IconFunnelFill,
  gift: IconGift,
  "gift-fill": IconGiftFill,
  globe: IconGlobe,
  "globe-2": IconGlobe2,
  "globe-2-fill": IconGlobe2Fill,
  gpu: IconGpu,
  "gpu-fill": IconGpuFill,
  "gpu-offering": IconGpuOffering,
  "gpu-offering-fill": IconGpuOfferingFill,
  grid: IconGrid,
  "grid-2": IconGrid2,
  "grid-fill": IconGridFill,
  group: IconGroup,
  "group-fill": IconGroupFill,
  "hard-disk-image": IconHardDiskImage,
  "hard-drive": IconHardDrive,
  "hard-drive-fill": IconHardDriveFill,
  "hard-drive-offering": IconHardDriveOffering,
  "hard-drives": IconHardDrives,
  hash: IconHash,
  hastrategic: IconHastrategic,
  "hastrategic-zsv": IconHastrategicZsv,
  headphones: IconHeadphones,
  "headphones-fill": IconHeadphonesFill,
  heart: IconHeart,
  "heart-fill": IconHeartFill,
  height: IconHeight,
  history: IconHistory,
  "history-fill": IconHistoryFill,
  home: IconHome,
  "home-fill": IconHomeFill,
  hourglass: IconHourglass,
  image: IconImage,
  "image-fill": IconImageFill,
  inbox: IconInbox,
  "inbox-fill": IconInboxFill,
  "inference-template": IconInferenceTemplate,
  info: IconInfo,
  "info-fill": IconInfoFill,
  interface: IconInterface,
  "interface-fill": IconInterfaceFill,
  ip: IconIp,
  "ip-2": IconIp2,
  "ip-fill": IconIpFill,
  italic: IconItalic,
  "kernel-portgroup": IconKernelPortgroup,
  key: IconKey,
  "key-fill": IconKeyFill,
  keypad: IconKeypad,
  "keypad-fill": IconKeypadFill,
  knife: IconKnife,
  kylin: IconKylin,
  layers: IconLayers,
  "layers-fill": IconLayersFill,
  layout: IconLayout,
  "layout-fill": IconLayoutFill,
  "layout-left": IconLayoutLeft,
  link: IconLink,
  linked: IconLinked,
  linux: IconLinux,
  list: IconList,
  "list-numeral": IconListNumeral,
  llmops: IconLlmops,
  loader: IconLoader,
  locate: IconLocate,
  lock: IconLock,
  "lock-fill": IconLockFill,
  "log-collect": IconLogCollect,
  "log-in": IconLogIn,
  "log-out": IconLogOut,
  "mail-receive": IconMailReceive,
  "mail-receive-fill": IconMailReceiveFill,
  map: IconMap,
  "map-fill": IconMapFill,
  maximize: IconMaximize,
  "maximize-fill": IconMaximizeFill,
  memory: IconMemory,
  menu: IconMenu,
  "menu-2": IconMenu2,
  "menu-arrow-left": IconMenuArrowLeft,
  "menu-arrow-right": IconMenuArrowRight,
  "message-circle": IconMessageCircle,
  "message-circle-fill": IconMessageCircleFill,
  "message-square": IconMessageSquare,
  "message-square-fill": IconMessageSquareFill,
  mic: IconMic,
  "mic-fill": IconMicFill,
  "mic-off": IconMicOff,
  "mic-off-fill": IconMicOffFill,
  migrate: IconMigrate,
  "migrate-fill": IconMigrateFill,
  "migration-resource": IconMigrationResource,
  "migration-service": IconMigrationService,
  "migration-service-fill": IconMigrationServiceFill,
  minimize: IconMinimize,
  "minimize-fill": IconMinimizeFill,
  minus: IconMinus,
  "minus-circle": IconMinusCircle,
  "minus-circle-fill": IconMinusCircleFill,
  "minus-square": IconMinusSquare,
  "minus-square-fill": IconMinusSquareFill,
  "model-square": IconModelSquare,
  "model-test": IconModelTest,
  monitor: IconMonitor,
  "monitor-fill": IconMonitorFill,
  "monitor-offering": IconMonitorOffering,
  "monitor-offering-fill": IconMonitorOfferingFill,
  monitors: IconMonitors,
  moon: IconMoon,
  "moon-fill": IconMoonFill,
  "more-horizontal": IconMoreHorizontal,
  "more-vertical": IconMoreVertical,
  move: IconMove,
  music: IconMusic,
  "music-fill": IconMusicFill,
  "my-approvals": IconMyApprovals,
  navigation: IconNavigation,
  "navigation-2": IconNavigation2,
  "navigation-2-fill": IconNavigation2Fill,
  "navigation-fill": IconNavigationFill,
  "network-card": IconNetworkCard,
  "network-port": IconNetworkPort,
  "network-port-unfill": IconNetworkPortUnfill,
  node: IconNode,
  "node-2": IconNode2,
  "node-2-fill": IconNode2Fill,
  "node-3": IconNode3,
  "node-fill": IconNodeFill,
  npm: IconNpm,
  "npm-fill": IconNpmFill,
  nut: IconNut,
  "nut-fill": IconNutFill,
  openeuler: IconOpeneuler,
  opensuse: IconOpensuse,
  options: IconOptions,
  "options-2": IconOptions2,
  "options-2-fill": IconOptions2Fill,
  "options-fill": IconOptionsFill,
  oracle: IconOracle,
  outlet: IconOutlet,
  "outlet-fill": IconOutletFill,
  pantone: IconPantone,
  "pantone-fill": IconPantoneFill,
  "paper-plane": IconPaperPlane,
  parameter: IconParameter,
  "parameter-off": IconParameterOff,
  paravirtualization: IconParavirtualization,
  "paravirtualization-fill": IconParavirtualizationFill,
  "pause-circle": IconPauseCircle,
  "pause-circle-fill": IconPauseCircleFill,
  people: IconPeople,
  "people-fill": IconPeopleFill,
  percent: IconPercent,
  person: IconPerson,
  "person-add": IconPersonAdd,
  "person-add-fill": IconPersonAddFill,
  "person-admin": IconPersonAdmin,
  "person-admin-fill": IconPersonAdminFill,
  "person-circle": IconPersonCircle,
  "person-circle-fill": IconPersonCircleFill,
  "person-delete": IconPersonDelete,
  "person-delete-fill": IconPersonDeleteFill,
  "person-done": IconPersonDone,
  "person-done-fill": IconPersonDoneFill,
  "person-fill": IconPersonFill,
  "person-remove": IconPersonRemove,
  "person-remove-fill": IconPersonRemoveFill,
  phone: IconPhone,
  "phone-call": IconPhoneCall,
  "phone-call-fill": IconPhoneCallFill,
  "phone-fill": IconPhoneFill,
  "phone-missed": IconPhoneMissed,
  "phone-missed-fill": IconPhoneMissedFill,
  "phone-off": IconPhoneOff,
  "phone-off-fill": IconPhoneOffFill,
  "pie-chart": IconPieChart,
  "pie-chart-fill": IconPieChartFill,
  pin: IconPin,
  "pin-2": IconPin2,
  "pin-fill": IconPinFill,
  "play-circle": IconPlayCircle,
  "play-circle-fill": IconPlayCircleFill,
  plugin: IconPlugin,
  plus: IconPlus,
  "plus-circle": IconPlusCircle,
  "plus-circle-fill": IconPlusCircleFill,
  "plus-square": IconPlusSquare,
  "plus-square-fill": IconPlusSquareFill,
  power: IconPower,
  pricetag: IconPricetag,
  "pricetag-fill": IconPricetagFill,
  pricetags: IconPricetags,
  printer: IconPrinter,
  "printer-fill": IconPrinterFill,
  progress: IconProgress,
  "progress-fill": IconProgressFill,
  qcode: IconQcode,
  "question-mark": IconQuestionMark,
  "question-mark-circle": IconQuestionMarkCircle,
  "question-mark-circle-fill": IconQuestionMarkCircleFill,
  questionnaire: IconQuestionnaire,
  radio: IconRadio,
  "radio-button-off": IconRadioButtonOff,
  "radio-button-off-disabled": IconRadioButtonOffDisabled,
  "radio-button-on": IconRadioButtonOn,
  "radio-button-on-fill": IconRadioButtonOnFill,
  "radio-fill": IconRadioFill,
  recovery: IconRecovery,
  redhat: IconRedhat,
  redo: IconRedo,
  "redo-fill": IconRedoFill,
  refresh: IconRefresh,
  repeat: IconRepeat,
  restore: IconRestore,
  "rewind-left": IconRewindLeft,
  "rewind-left-fill": IconRewindLeftFill,
  "rewind-right": IconRewindRight,
  "rewind-right-fill": IconRewindRightFill,
  rockylinux: IconRockylinux,
  router: IconRouter,
  "router-fill": IconRouterFill,
  "router-launch": IconRouterLaunch,
  "router-launch-fill": IconRouterLaunchFill,
  "router-offering": IconRouterOffering,
  "router-offering-fill": IconRouterOfferingFill,
  routers: IconRouters,
  "routers-fill": IconRoutersFill,
  scan: IconScan,
  scissors: IconScissors,
  "script-library": IconScriptLibrary,
  search: IconSearch,
  select: IconSelect,
  server: IconServer,
  "server-1": IconServer1,
  "server-1-fill": IconServer1Fill,
  "server-2": IconServer2,
  "server-2-fill": IconServer2Fill,
  "server-3": IconServer3,
  "server-3-fill": IconServer3Fill,
  "server-4": IconServer4,
  "server-fill": IconServerFill,
  "servers-3": IconServers3,
  settings: IconSettings,
  "settings-2": IconSettings2,
  "settings-2-fill": IconSettings2Fill,
  "settings-fill": IconSettingsFill,
  shake: IconShake,
  share: IconShare,
  "share-fill": IconShareFill,
  shield: IconShield,
  "shield-1": IconShield1,
  "shield-2-fill": IconShield2Fill,
  "shield-fill": IconShieldFill,
  "shield-off": IconShieldOff,
  "shield-off-fill": IconShieldOffFill,
  "shopping-bag": IconShoppingBag,
  "shopping-bag-fill": IconShoppingBagFill,
  "shopping-cart": IconShoppingCart,
  "shopping-cart-fill": IconShoppingCartFill,
  shuffle: IconShuffle,
  "shuffle-2": IconShuffle2,
  "shutter-fill": IconShutterFill,
  "skip-back": IconSkipBack,
  "skip-back-fill": IconSkipBackFill,
  "skip-forward": IconSkipForward,
  "skip-forward-fill": IconSkipForwardFill,
  slash: IconSlash,
  slot: IconSlot,
  "slot-fill": IconSlotFill,
  smartphone: IconSmartphone,
  "smartphone-fill": IconSmartphoneFill,
  snmp: IconSnmp,
  socket: IconSocket,
  "socket-fill": IconSocketFill,
  solaris: IconSolaris,
  sort: IconSort,
  source: IconSource,
  "source-fill": IconSourceFill,
  "source-group": IconSourceGroup,
  "source-group-fill": IconSourceGroupFill,
  speaker: IconSpeaker,
  "speaker-fill": IconSpeakerFill,
  square: IconSquare,
  stablity: IconStablity,
  "stablity-fill": IconStablityFill,
  star: IconStar,
  "star-fill": IconStarFill,
  "stop-circle": IconStopCircle,
  "stop-circle-fill": IconStopCircleFill,
  storage: IconStorage,
  "storage-2": IconStorage2,
  "storage-2-fill": IconStorage2Fill,
  "storage-3": IconStorage3,
  "storage-3-fill": IconStorage3Fill,
  "storage-4": IconStorage4,
  "storage-fill": IconStorageFill,
  subset: IconSubset,
  "subset-fill": IconSubsetFill,
  success: IconSuccess,
  sun: IconSun,
  "sun-fill": IconSunFill,
  suse: IconSuse,
  sustain: IconSustain,
  swap: IconSwap,
  "swap-2": IconSwap2,
  sync: IconSync,
  "system-translation": IconSystemTranslation,
  "system-translation-fill": IconSystemTranslationFill,
  tags: IconTags,
  "tags-fill": IconTagsFill,
  task: IconTask,
  text: IconText,
  thermometer: IconThermometer,
  "thermometer-fill": IconThermometerFill,
  "thermometer-minus": IconThermometerMinus,
  "thermometer-minus-fill": IconThermometerMinusFill,
  "thermometer-plus": IconThermometerPlus,
  "thermometer-plus-fill": IconThermometerPlusFill,
  "timed-task": IconTimedTask,
  "timed-task-fill": IconTimedTaskFill,
  timer: IconTimer,
  "timer-fill": IconTimerFill,
  "to-bottom": IconToBottom,
  "toggle-left": IconToggleLeft,
  "toggle-left-fill": IconToggleLeftFill,
  "toggle-right": IconToggleRight,
  "toggle-right-fill": IconToggleRightFill,
  topology: IconTopology,
  "topology-2": IconTopology2,
  "topology-2-fill": IconTopology2Fill,
  "topology-fill": IconTopologyFill,
  "to-top": IconToTop,
  trash: IconTrash,
  "trash-fill": IconTrashFill,
  tree: IconTree,
  "trending-down": IconTrendingDown,
  "trending-up": IconTrendingUp,
  tunnel: IconTunnel,
  "tunnel-fill": IconTunnelFill,
  tv: IconTv,
  "tv-fill": IconTvFill,
  ubuntu: IconUbuntu,
  umbrella: IconUmbrella,
  "umbrella-fill": IconUmbrellaFill,
  underline: IconUnderline,
  undo: IconUndo,
  "undo-fill": IconUndoFill,
  ungroup: IconUngroup,
  "ungroup-fill": IconUngroupFill,
  unlock: IconUnlock,
  "unlock-fill": IconUnlockFill,
  uos: IconUos,
  upload: IconUpload,
  usb: IconUsb,
  "user-registration-term-bg": IconUserRegistrationTermBg,
  vcenter: IconVcenter,
  version: IconVersion,
  "version-checkbg": IconVersionCheckbg,
  vessel: IconVessel,
  "vessel-fill": IconVesselFill,
  "vgpu-offering": IconVgpuOffering,
  "vgpu-offering-fill": IconVgpuOfferingFill,
  video: IconVideo,
  "video-fill": IconVideoFill,
  "video-off": IconVideoOff,
  "video-off-fill": IconVideoOffFill,
  volume: IconVolume,
  "volume-down": IconVolumeDown,
  "volume-down-fill": IconVolumeDownFill,
  "volume-fill": IconVolumeFill,
  "volume-off": IconVolumeOff,
  "volume-off-fill": IconVolumeOffFill,
  "volume-up": IconVolumeUp,
  "volume-up-fill": IconVolumeUpFill,
  vyos: IconVyos,
  wall: IconWall,
  "wall-fill": IconWallFill,
  "web-shell": IconWebShell,
  weight: IconWeight,
  "weight-fill": IconWeightFill,
  wifi: IconWifi,
  "wifi-off": IconWifiOff,
  windows: IconWindows,
  wizard: IconWizard,
  wrench: IconWrench,
  "wrench-circle-fill": IconWrenchCircleFill,
  "wrench-fill": IconWrenchFill,
  "xml-hook": IconXmlHook,
} satisfies Record<string, IconComponent>;
