export enum PicNicStatus {
  Connected = "Connected",
  Notconnected = "Notconnected",
}

export enum PciDeviceVirtStatus {
  VIRTUALIZED_BYPASS_ZSTACK = "VIRTUALIZED_BYPASS_ZSTACK",
  UNVIRTUALIZABLE = "UNVIRTUALIZABLE",
  SRIOV_VIRTUALIZABLE = "SRIOV_VIRTUALIZABLE",
  VFIO_MDEV_VIRTUALIZABLE = "VFIO_MDEV_VIRTUALIZABLE",
  SRIOV_VIRTUALIZED = "SRIOV_VIRTUALIZED",
  VFIO_MDEV_VIRTUALIZED = "VFIO_MDEV_VIRTUALIZED",
  UNKNOWN = "UNKNOWN",
}
