fragment zoneFieldsInMain on Zone {
  uuid
  name
  description
  state
  isDefault
  createDate
}

fragment errorFields on ActionError {
  code
}

query zone($uuid: String!) {
  zone(uuid: $uuid) {
    clusterCount
    primaryStorageCount
    l2NetworkCount
    vmInstanceCount
    volumeCount
    ...zoneFieldsInMain
  }
}

query zoneRelatedSummary($uuid: String!) {
  zoneRelatedSummary(uuid: $uuid) {
    clusterTotal
    l2NetworkTotal
    primaryStorageTotal
    backupStorageTotal
  }
}

query zoneList($conditions: [Condition!], $start: Int, $limit: Int) {
  zoneList(
    conditions: $conditions
    start: $start
    limit: $limit
    replyWithCount: true
    sortDirection: asc
  ) {
    total
    list {
      clusterCount
      primaryStorageCount
      l2NetworkCount
      vmInstanceCount
      volumeCount
      ...zoneFieldsInMain
    }
  }
}

mutation createZone($input: CreateZoneInput!) {
  createZone(input: $input) {
    actionId
  }
}

mutation deleteZone($input: DeleteZoneInput!) {
  deleteZone(input: $input) {
    actionId
  }
}

mutation changeZoneState($input: ChangeZoneStateInput!) {
  changeZoneState(input: $input) {
    actionId
  }
}

mutation updateZone($input: UpdateZoneInput!) {
  updateZone(input: $input) {
    actionId
  }
}
