query moduleAuthorizationDetailsList(
  $start: Int
  $limit: Int
  $sortBy: String
  $sortDirection: SortDirectionValidValues
) {
  moduleAuthorizationDetailsList(
    start: $start
    limit: $limit
    sortBy: $sortBy
    sortDirection: $sortDirection
    replyWithCount: true
  ) {
    list {
      uuid
      key
      type
      activated
      count
      expired_date
      consumed
      is_active
      name
      email
      status
      is_valid
      comment
      vendor
    }
    total
  }
}
