const mapping: [string, string][] = [
  ["a", "KeyA"],
  ["b", "KeyB"],
  ["c", "KeyC"],
  ["d", "KeyD"],
  ["e", "KeyE"],
  ["f", "KeyF"],
  ["g", "KeyG"],
  ["h", "KeyH"],
  ["i", "KeyI"],
  ["j", "KeyJ"],
  ["k", "KeyK"],
  ["l", "KeyL"],
  ["m", "KeyM"],
  ["n", "KeyN"],
  ["o", "KeyO"],
  ["p", "KeyP"],
  ["q", "KeyQ"],
  ["r", "KeyR"],
  ["s", "KeyS"],
  ["t", "KeyT"],
  ["u", "KeyU"],
  ["v", "KeyV"],
  ["w", "KeyW"],
  ["x", "KeyX"],
  ["y", "KeyY"],
  ["z", "KeyZ"],
  ["1", "Digit1"],
  ["2", "Digit2"],
  ["3", "Digit3"],
  ["4", "Digit4"],
  ["5", "Digit5"],
  ["6", "Digit6"],
  ["7", "Digit7"],
  ["8", "Digit8"],
  ["9", "Digit9"],
  ["0", "Digit0"],
  ["enter", "Enter"],
  ["esc", "Escape"],
  ["backspace", "Backspace"],
  ["tab", "Tab"],
  ["space", "Space"],
  ["-", "Minus"],
  ["=", "Equal"],
  ["[", "BracketLeft"],
  ["]", "BracketRight"],
  ["\\", "Backslash"],
  [";", "Semicolon"],
  ["'", "Quote"],
  ["`", "Backquote"],
  [",", "Comma"],
  [".", "Period"],
  ["/", "Slash"],
  ["f1", "F1"],
  ["f2", "F2"],
  ["f3", "F3"],
  ["f4", "F4"],
  ["f5", "F5"],
  ["f6", "F6"],
  ["f7", "F7"],
  ["f8", "F8"],
  ["f9", "F9"],
  ["f10", "F10"],
  ["f11", "F11"],
  ["f12", "F12"],
  ["insert", "Insert"],
  ["home", "Home"],
  ["end", "End"],
  ["pageUp", "PageUp"],
  ["pageDown", "PageDown"],
  ["delete", "Delete"],
  ["left", "ArrowLeft"],
  ["right", "ArrowRight"],
  ["up", "ArrowUp"],
  ["down", "ArrowDown"],
  ["menu", "ContextMenu"],
];

export const keyCodeMap = new Map(mapping);

export const functionKeys = new Set([
  "Enter",
  "Escape",
  "Tab",
  "Insert",
  "Delete",
  "Home",
  "End",
  "PageUp",
  "PageDown",
  "ArrowUp",
  "ArrowDown",
  "ArrowLeft",
  "ArrowRight",
  "F1",
  "F2",
  "F3",
  "F4",
  "F5",
  "F6",
  "F7",
  "F8",
  "F9",
  "F10",
  "F11",
  "F12",
  "ContextMenu",
]);
