fragment CBDPrimaryStoragePoolFields on CBDPrimaryStoragePool {
  uuid
  logicalPoolName
  createTime
  availableCapacity
  capacity
  replicaNum
  cbdPrimaryStoragePoolCapacity {
    volumeSnapshotSize
    imageCacheSize
    volumeSize
    volumeActualSize
    vmTemplateVolumeCacheSize
    reservedCapacity
  }
  primaryStorageCapacity {
    reservedCapacity
    overProvisioningPrimaryStorage
    thresholdPrimaryStoragePhysicalCapacity
    totalPhysicalCapacity
    availablePhysicalCapacity
  }
}

query cbdPrimaryStoragePoolList(
  $start: Int
  $limit: Int
  $conditions: [Condition!]
  $extraConditions: [Condition!]
  $sortBy: String
  $sortDirection: SortDirectionValidValues
  $type: CBDPrimaryStoragePoolQueryType
) {
  cbdPrimaryStoragePoolList(
    start: $start
    limit: $limit
    conditions: $conditions
    extraConditions: $extraConditions
    sortBy: $sortBy
    sortDirection: $sortDirection
    type: $type
    replyWithCount: true
  ) {
    total
    list {
      ...CBDPrimaryStoragePoolFields
    }
  }
}
