

query getGroupDirTreeByUuid($conditions: [Condition!]) {
  getGroupDirTreeByUuid(conditions: $conditions) {
    list {
      key
      title
      level
      name
      parentUuid
      zoneUuid
      uuid
      groupName
      vmCount
      createDate
    }
  }
}
