fragment ExternalPrimaryStoragePoolFields on ExternalPrimaryStoragePool {
  uuid
  name
  aliasName
  createDate
  availableCapacity
  diskUtilization
  redundancyPolicy
  replicatedSize
  totalCapacity
  usedCapacity
  externalPrimaryStoragePoolCapacity {
    volumeSnapshotSize
    imageCacheSize
    volumeSize
    volumeActualSize
    vmTemplateVolumeCacheSize
    reservedCapacity
  }
  primaryStorageCapacity {
    reservedCapacity
    overProvisioningPrimaryStorage
    thresholdPrimaryStoragePhysicalCapacity
    totalPhysicalCapacity
    availablePhysicalCapacity
  }
}

query externalPrimaryStoragePoolList(
  $start: Int
  $limit: Int
  $conditions: [Condition!]
  $extraConditions: [Condition!]
  $sortBy: String
  $sortDirection: SortDirectionValidValues
  $type: String
) {
  externalPrimaryStoragePoolList(
    start: $start
    limit: $limit
    conditions: $conditions
    extraConditions: $extraConditions
    sortBy: $sortBy
    sortDirection: $sortDirection
    type: $type
    replyWithCount: true
  ) {
    total
    list {
      ...ExternalPrimaryStoragePoolFields
    }
  }
}

mutation addExternalPrimaryStoragePool($input: AddExternalPrimaryStoragePoolInput!) {
  addExternalPrimaryStoragePool(input: $input) {
    actionId
  }
}

mutation deleteExternalPrimaryStoragePool($input: DeleteExternalPrimaryStoragePoolInput!) {
  deleteExternalPrimaryStoragePool(input: $input) {
    actionId
  }
}

mutation updateExternalPrimaryStoragePool($input: UpdateExternalPrimaryStoragePoolInput!) {
  updateExternalPrimaryStoragePool(input: $input) {
    actionId
  }
}
