mutation createInstance($input: CreateInstanceInput!) {
  createInstance(input: $input) {
    actionId
  }
}

mutation createVMFromTemplate($input: CreateVMFromTemplateInput!) {
  createVMFromTemplate(input: $input) {
    actionId
  }
}

query getStorageMigrateVmInstancesDepends($uuids: [String!]!) {
  batchStorageMigrateVmInstancedepends(uuids: $uuids) {
    isAttachedScsiLunDevice
    hasUnavailableUsbDevice
    hasPeripheralAttached
    uuid
  }
}
query instanceBasicInfo(
  $conditions: [Condition!]
  $start: Int
  $limit: Int
  $type: VmQueryType
  $extraConditions: [Condition!] = []
  $sortBy: String
  $sortDirection: SortDirectionValidValues
) {
  vmInstanceList(
    start: $start
    limit: $limit
    replyWithCount: true
    conditions: $conditions
    type: $type
    extraConditions: $extraConditions
    sortBy: $sortBy
    sortDirection: $sortDirection
  ) {
    list {
      uuid
      name
      architecture
      crashStrategy
      cpuNum
      memorySize
      description
      clusterUuid
      rootVolumeUuid
      platform
      guestOsType
      defaultL3NetworkUuid
      imageUuid
      lastHostUuid
      hostUuid
      backupStatus
      backupTaskStatus
      reservedMemorySize
      defaultL3Network {
        name
        uuid
        ipVersion
        networkType
      }

      systemTag {
        cpuCores
        cpuSockets
        haStickStragedy
        sshkey
        bootOrder
        bootOrderOnce
        consolePassword
        vmConsoleMode
        vmPriority
        GuestTools
        bootMode
        RDPEnable
        usbRedirect
        qemuga
        antiSpoofing
        VDIMonitorNumber
        userdata
        clockTrack
        timeTrack
        vmDriver
        hostname
        qxlMemory {
          ram
          vram
          vgamem
        }
      }
      vmHa {
        haLevel
      }
      zoneUuid
      group {
        groupName
        uuid
      }
    }
  }
}

fragment vmInstanceDetailFields on VmInstance {
  uuid
  name
  healthStatus
  architecture
  crashStrategy
  type
  metric {
    time
    value
  }
  toolsState
  vnuma
  hypervisorType
  cpuNum
  memorySize
  createDate
  lastOpDate
  description
  state
  clusterUuid
  rootVolumeUuid
  attachedShareableVolumeUuidList
  platform
  guestOsType
  guestToolsState {
    osType
    platform
    qgaState
    version
    zwatchState
    vmInstanceUuid
  }
  defaultL3NetworkUuid
  imageUuid
  lastHostUuid
  hostUuid
  backupStatus
  backupTaskStatus
  reservedMemorySize
  defaultL3Network {
    name
    uuid
    ipVersion
    networkType
  }
  # capabilities {
  #   LiveMigration
  #   MemorySnapshot
  #   Reimage
  #   VolumeMigration
  # }

  backupTaskType
  owner {
    uuid
    name
    type
    linkedAccountUuid
  }
  cluster {
    name
    state
    uuid
  }
  host {
    uuid
    name
    state
    status
    managementIp
    cpuNum
    clusterUuid
  }
  lastHost {
    uuid
    name
    state
    managementIp
  }
  sshKeyPairNum
  image {
    name
    uuid
    status
  }
  primaryStorage {
    name
    uuid
    type
    state
    defaultProtocol
    availableCapacity
  }
  tag {
    ownerUuid
    name
    uuid
    color
  }
  vmNics {
    type
    uuid
    mac
    ip
    deviceId
    usedIps {
      uuid
      ip
      ipVersion
      l3NetworkUuid
    }
    l3NetworkUuid
    l3Network {
      ... on L3Network {
        name
        uuid
        l2NetworkUuid
        l2Network {
          uuid
          vSwitchType
        }
        networkServices {
          networkServiceType
        }
      }
    }
  }
  eip {
    uuid
    name
    vipIp
  }
  toolsInfo {
    lowVersion
    version
  }
  allVolumes {
    uuid
    name
    deviceId
    lastAttachDate
    primaryStorageUuid
    size
    actualSize
    isShareable
    type
    installPath
    primaryStorage {
      type
      uuid
      name
      defaultProtocol
    }
  }
  gpuDeviceSpec {
    name
    isVirtual
    type
    uuid
    deviceType
  }
  systemTag {
    cpuCores
    cpuSockets
    haStickStragedy
    sshkey
    bootOrder
    bootOrderOnce
    consolePassword
    vmConsoleMode
    vmPriority
    GuestTools
    bootMode
    RDPEnable
    usbRedirect
    qemuga
    antiSpoofing
    VDIMonitorNumber
    userdata
    clockTrack
    timeTrack
    isoList {
      uuid
      index
    }
    vmCpuPinningList {
      vCPU
      pCPU
    }
    staticIp {
      l3NetworkUuid
      ip
    }
    vmDriver
    hostname
    qxlMemory {
      ram
      vram
      vgamem
    }
    vmMachineType
  }
  vmHa {
    haLevel
  }
  vmCdRoms {
    uuid
    isoUuid
  }
  zoneUuid
  relatedResource {
    backupData
  }
  # cdpTaskStatus
  exportInfo {
    uuid
    name
    exportUrl
    createDate
    size
  }
  vmGroup {
    uuid
    name
    vmSchedulingRuleCount
    associatedVmSchedulingRuleList {
      uuid
      name
      rule
      mode
      hostGroup {
        uuid
        name
      }
    }
    vmCount
  }
  schedulingState
  group {
    groupName
    uuid
  }
  qemuState
  haveScsiLun
  lastBackupJobResult {
    id
    fireInstanceId
    success
    resultDump
  }
  localBackupCount
  localBackupCapacity
  backupJob {
    uuid
    jobData
    state
    schedulerJobGroupJobRefs {
      schedulerJobGroupUuid
      priority
    }
    schedulerJobGroup {
      uuid
      name
    }
  }
  shareType
  userGroup {
    uuid
    name
  }
  lastOpDate
}

query vmInstanceDetail($uuid: String!) {
  vmInstance(uuid: $uuid) {
    volumeAttributeUserConfig
    emulatorPin
    sshKeyPairs {
      uuid
      name
    }
    securityGroup {
      name
      uuid
    }
    cpuModeInfo {
      value
      dependentResourceType
    }
    hasTopology
    vmCdRoms {
      uuid
      isoUuid
    }
    consoleAddress
    bootOrder {
      orders
    }
    snapshotSchedulerJob {
      uuid
      name
    }
    uptime
    tpmList {
      uuid
      vmInstanceUuid
    }
    ...vmInstanceDetailFields
  }
}

query guestToolsInfoInVMDetail($uuid: String!) {
  guestToolInfo(uuid: $uuid) {
    lowVersion
    features {
      pvpanic
      pvpanic_host_enable
      pvpanic_guest_tools_enable
      pvpanic_guest_kernel_supported
    }
    status
  }
}

query templatedVmInstanceList(
  $conditions: [Condition!]
  $start: Int
  $limit: Int
  $type: VmQueryType
  $extraConditions: [Condition!] = []
  $sortBy: String
  $sortDirection: SortDirectionValidValues
) {
  vmInstanceList(
    start: $start
    limit: $limit
    replyWithCount: true
    conditions: $conditions
    type: $type
    extraConditions: $extraConditions
    sortBy: $sortBy
    sortDirection: $sortDirection
  ) {
    total
    list {
      vmUsage {
        cpuUsed
        memoryUsed
        storageUsed
      }
      cpuModeInfo {
        value
        dependentResourceType
      }
      isTemplate
      ...instanceFields
    }
  }
}

fragment instanceFields on VmInstance {
  uuid
  name
  healthStatus
  architecture
  crashStrategy
  type
  metric {
    time
    value
  }
  toolsState
  vnuma
  hypervisorType
  cpuNum
  memorySize
  createDate
  lastOpDate
  description
  state
  clusterUuid
  rootVolumeUuid
  attachedShareableVolumeUuidList
  platform
  guestOsType
  guestToolsState {
    osType
    platform
    qgaState
    version
    zwatchState
    vmInstanceUuid
  }
  defaultL3NetworkUuid
  imageUuid
  lastHostUuid
  hostUuid
  backupStatus
  backupTaskStatus
  reservedMemorySize
  defaultL3Network {
    name
    uuid
    ipVersion
    networkType
  }
  # capabilities {
  #   LiveMigration
  #   MemorySnapshot
  #   Reimage
  #   VolumeMigration

  backupTaskType
  owner {
    uuid
    name
    type
    linkedAccountUuid
  }
  cluster {
    name
    state
    uuid
  }
  host {
    uuid
    name
    state
    status
    managementIp
    cpuNum
    clusterUuid
  }
  lastHost {
    uuid
    name
    state
    managementIp
  }
  sshKeyPairNum
  image {
    name
    uuid
    status
  }
  primaryStorage {
    name
    uuid
    type
    state
    availableCapacity
  }
  tag {
    ownerUuid
    name
    uuid
    color
  }
  vmNics {
    type
    uuid
    mac
    ip
    deviceId
    usedIps {
      uuid
      ip
      ipVersion
      l3NetworkUuid
    }
    l3NetworkUuid
    l3Network {
      ... on L3Network {
        name
        uuid
        l2NetworkUuid
        l2Network {
          uuid
          vSwitchType
        }
        networkServices {
          networkServiceType
        }
      }
    }
  }
  eip {
    uuid
    name
    vipIp
  }
  toolsInfo {
    lowVersion
    version
  }
  allVolumes {
    uuid
    name
    deviceId
    lastAttachDate
    primaryStorageUuid
    size
    actualSize
    isShareable
    type
    installPath
    primaryStorage {
      type
      uuid
      name
      defaultProtocol
    }
  }
  gpuDeviceSpec {
    name
    isVirtual
    type
    uuid
    deviceType
  }
  systemTag {
    cpuCores
    cpuSockets
    haStickStragedy
    sshkey
    bootOrder
    bootOrderOnce
    consolePassword
    vmConsoleMode
    vmPriority
    GuestTools
    bootMode
    RDPEnable
    usbRedirect
    qemuga
    antiSpoofing
    VDIMonitorNumber
    userdata
    clockTrack
    timeTrack
    isoList {
      uuid
      index
    }
    vmCpuPinningList {
      vCPU
      pCPU
    }
    staticIp {
      l3NetworkUuid
      ip
    }
    vmDriver
    hostname
    qxlMemory {
      ram
      vram
      vgamem
    }
  }
  vmHa {
    haLevel
  }
  vmCdRoms {
    uuid
    isoUuid
  }
  zoneUuid
  zone {
    uuid
    name
  }
  relatedResource {
    backupData
  }
  # cdpTaskStatus
  exportInfo {
    uuid
    name
    exportUrl
    createDate
    size
  }
  vmGroup {
    uuid
    name
    vmSchedulingRuleCount
    associatedVmSchedulingRuleList {
      uuid
      name
      rule
      mode
      hostGroup {
        uuid
        name
      }
    }
    vmCount
  }
  schedulingState
  group {
    groupName
    uuid
  }
  qemuState
  haveScsiLun
  lastBackupJobResult {
    id
    fireInstanceId
    success
    resultDump
  }
  localBackupCount
  localBackupCapacity
  backupJob {
    uuid
    jobData
    state
    schedulerJobGroupJobRefs {
      schedulerJobGroupUuid
      priority
    }
    schedulerJobGroup {
      uuid
      name
    }
  }
  shareType
  userGroup {
    uuid
    name
  }
  lastOpDate
}

query vmInstanceList(
  $conditions: [Condition!]
  $start: Int
  $limit: Int
  $type: VmQueryType
  $extraConditions: [Condition!] = []
  $sortBy: String
  $sortDirection: SortDirectionValidValues
) {
  vmInstanceList(
    start: $start
    limit: $limit
    replyWithCount: true
    conditions: $conditions
    type: $type
    extraConditions: $extraConditions
    sortBy: $sortBy
    sortDirection: $sortDirection
  ) {
    total
    list {
      vmUsage {
        cpuUsed
        memoryUsed
        storageUsed
      }
      snapshotSchedulerJob {
        uuid
      }
      ...instanceFields
    }
  }
}

query templatedVmInstanceList(
  $conditions: [Condition!]
  $start: Int
  $limit: Int
  $type: VmQueryType
  $extraConditions: [Condition!] = []
  $sortBy: String
  $sortDirection: SortDirectionValidValues
) {
  vmInstanceList(
    start: $start
    limit: $limit
    replyWithCount: true
    conditions: $conditions
    type: $type
    extraConditions: $extraConditions
    sortBy: $sortBy
    sortDirection: $sortDirection
  ) {
    total
    list {
      vmUsage {
        cpuUsed
        memoryUsed
        storageUsed
      }
      cpuModeInfo {
        value
        dependentResourceType
      }
      isTemplate
      ...instanceFields
    }
  }
}

fragment instanceFields on VmInstance {
  uuid
  name
  healthStatus
  architecture
  crashStrategy
  type
  metric {
    time
    value
  }
  toolsState
  vnuma
  hypervisorType
  cpuNum
  memorySize
  createDate
  lastOpDate
  description
  state
  clusterUuid
  rootVolumeUuid
  attachedShareableVolumeUuidList
  platform
  guestOsType
  guestToolsState {
    osType
    platform
    qgaState
    version
    zwatchState
    vmInstanceUuid
  }
  defaultL3NetworkUuid
  imageUuid
  lastHostUuid
  hostUuid
  backupStatus
  backupTaskStatus
  reservedMemorySize
  defaultL3Network {
    name
    uuid
    ipVersion
    networkType
  }
  # capabilities {
  #   LiveMigration
  #   MemorySnapshot
  #   Reimage
  #   VolumeMigration

  backupTaskType
  owner {
    uuid
    name
    type
    linkedAccountUuid
  }
  cluster {
    name
    state
    uuid
  }
  host {
    uuid
    name
    state
    status
    managementIp
    cpuNum
    clusterUuid
  }
  lastHost {
    uuid
    name
    state
    managementIp
  }
  sshKeyPairNum
  image {
    name
    uuid
    status
  }
  primaryStorage {
    name
    uuid
    type
    state
    availableCapacity
  }
  tag {
    ownerUuid
    name
    uuid
    color
  }
  vmNics {
    type
    uuid
    mac
    ip
    deviceId
    usedIps {
      uuid
      ip
      ipVersion
      l3NetworkUuid
    }
    l3NetworkUuid
    l3Network {
      ... on L3Network {
        name
        uuid
        l2NetworkUuid
        l2Network {
          uuid
          vSwitchType
        }
        networkServices {
          networkServiceType
        }
      }
    }
  }
  eip {
    uuid
    name
    vipIp
  }
  toolsInfo {
    lowVersion
    version
  }
  allVolumes {
    uuid
    name
    deviceId
    lastAttachDate
    primaryStorageUuid
    size
    actualSize
    isShareable
    type
    installPath
    primaryStorage {
      type
      uuid
      name
      defaultProtocol
    }
  }
  gpuDeviceSpec {
    name
    isVirtual
    type
    uuid
    deviceType
  }
  systemTag {
    cpuCores
    cpuSockets
    haStickStragedy
    sshkey
    bootOrder
    bootOrderOnce
    consolePassword
    vmConsoleMode
    vmPriority
    GuestTools
    bootMode
    RDPEnable
    usbRedirect
    qemuga
    antiSpoofing
    VDIMonitorNumber
    userdata
    clockTrack
    timeTrack
    isoList {
      uuid
      index
    }
    vmCpuPinningList {
      vCPU
      pCPU
    }
    staticIp {
      l3NetworkUuid
      ip
    }
    vmDriver
    hostname
    qxlMemory {
      ram
      vram
      vgamem
    }
  }
  vmHa {
    haLevel
  }
  vmCdRoms {
    uuid
    isoUuid
  }
  zoneUuid
  zone {
    uuid
    name
  }
  relatedResource {
    backupData
  }
  # cdpTaskStatus
  exportInfo {
    uuid
    name
    exportUrl
    createDate
    size
  }
  vmGroup {
    uuid
    name
    vmSchedulingRuleCount
    associatedVmSchedulingRuleList {
      uuid
      name
      rule
      mode
      hostGroup {
        uuid
        name
      }
    }
    vmCount
  }
  schedulingState
  group {
    groupName
    uuid
  }

  qemuState
  haveScsiLun
  lastBackupJobResult {
    id
    fireInstanceId
    success
    resultDump
  }
  localBackupCount
  localBackupCapacity
  backupJob {
    uuid
    jobData
    state
    schedulerJobGroupJobRefs {
      schedulerJobGroupUuid
      priority
    }
    schedulerJobGroup {
      uuid
      name
    }
  }
  shareType
  userGroup {
    uuid
    name
  }
  lastOpDate
}

query vmInstanceList(
  $conditions: [Condition!]
  $start: Int
  $limit: Int
  $type: VmQueryType
  $extraConditions: [Condition!] = []
  $sortBy: String
  $sortDirection: SortDirectionValidValues
) {
  vmInstanceList(
    start: $start
    limit: $limit
    replyWithCount: true
    conditions: $conditions
    type: $type
    extraConditions: $extraConditions
    sortBy: $sortBy
    sortDirection: $sortDirection
  ) {
    total
    list {
      vmUsage {
        cpuUsed
        memoryUsed
        storageUsed
      }
      snapshotSchedulerJob {
        uuid
      }
      ...instanceFields
    }
  }
}
