export const currentPlaceholder = {
  __typename: "VmTemplate",
  volumeAttributeUserConfig: null,
  emulatorPin: "0",
  securityGroup: [],
  portForwarding: null,
  cpuModeInfo: {
    __typename: "VmCpuMode",
    value: "none",
    dependentResourceType: "VmInstanceVO",
  },
  hasTopology: false,
  vmCdRoms: [],
  consoleAddress: [],
  bootOrder: { __typename: "BootOrderResp", orders: ["HardDisk"] },
  toolsInfo: {
    __typename: "GuestToolInfo",
    lowVersion: false,
    features: {
      __typename: "GuestToolFeatures",
      pvpanic: "disable",
      pvpanic_host_enable: "enable",
      pvpanic_guest_tools_enable: "not supported",
    },
    status: "Not Connected",
  },
  allVolumes: [
    { actualSize: 536870912, installPath: "", name: "", size: 0, uuid: "" },
  ],
  snapshotSchedulerJob: [],
  uuid: "",
  name: "",
  healthStatus: null,
  architecture: "x86_64",
  crashStrategy: "Preserve",
  type: "UserVm",
  metric: null,
  toolsState: "Uninstall",
  vnuma: false,
  hypervisorType: "KVM",
  cpuNum: 1,
  memorySize: 536870912,
  createDate: "",
  lastOpDate: "",
  description: "",
  state: "Running",
  clusterUuid: "",
  rootVolumeUuid: "",
  attachedShareableVolumeUuidList: [],
  platform: "Linux",
  guestOsType: "Linux",
  guestToolsState: {
    __typename: "GuestToolsStateInfo",
    osType: null,
    platform: null,
    qgaState: "NotInstalled",
    version: null,
    zwatchState: "NotInstalled",
    vmInstanceUuid: "",
  },
  defaultL3NetworkUuid: null,
  imageUuid: "",
  lastHostUuid: "",
  hostUuid: "",
  backupStatus: "Ready",
  defaultL3Network: null,
  capabilities: {
    __typename: "VmCapabilities",
    LiveMigration: false,
    MemorySnapshot: true,
    Reimage: true,
    VolumeMigration: false,
  },

  backupTaskType: null,
  owner: {
    __typename: "VmOwner",
    uuid: "",
    name: "",
    type: "",
    linkedAccountUuid: "",
  },
  cluster: {
    __typename: "",
    name: "",
    state: "",
    uuid: "",
  },
  host: {
    __typename: "",
    uuid: "",
    name: "",
    state: "",
    status: "",
    managementIp: "",
    cpuNum: 12,
  },
  lastHost: {
    __typename: "",
    uuid: "",
    name: "",
    managementIp: "",
  },
  image: {
    __typename: "",
    name: "",
    uuid: "",
    status: "",
  },
  primaryStorage: {
    __typename: "",
    name: "",
    uuid: "",
    type: "",
    state: "",
    availableCapacity: 0,
  },
  tag: [],
  vmNics: [],
  eip: [],
  gpuDeviceSpec: [],
  systemTag: {
    __typename: "VmInstanceSystemTag",
    cpuSockets: "1",
    haStickStragedy: true,
    ha: "NeverStop",
    sshkey: null,
    bootOrder: ["HardDisk"],
    bootOrderOnce: null,
    consolePassword: null,
    vmConsoleMode: "vnc",
    vmPriority: "Normal",
    GuestTools: null,
    bootMode: "Legacy",
    RDPEnable: null,
    usbRedirect: null,
    qemuga: null,
    antiSpoofing: null,
    VDIMonitorNumber: null,
    userdata: null,
    clockTrack: "host",
    timeTrack: "0",
    isoList: [],
    vmCpuPinningList: [],
    staticIp: [],
    vmDriver: true,
    hostname: null,
    qxlMemory: null,
  },
  zoneUuid: "",
  relatedResource: { __typename: "RelatedResource", backupData: 0 },
  cdpTaskStatus: null,
  exportInfo: null,
  vmGroup: null,
  schedulingState: null,
  group: {
    __typename: "VMGroupDirectory",
    groupName: "",
    uuid: "",
  },
  qemuState: "Matched",
  uptime: "",
};
