query queryWidgetAlarmInfo($conditions: [Condition!]) {
  queryWidgetAlarmInfo(conditions: $conditions) {
    emergentCount
    importantCount
    normalCount
    top5ResourceList {
      uuid
      namespace
      resourceInfo {
        resourceName
        resourceType
        state
      }
      emergent
      important
    }
  }
}
